# Generated by Django 2.1 on 2018-09-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collect.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collect.PersonalInfo'),
        ),
    ]
